<?php

/**
 * Implements hook_permission()
 */
function subscriptions_alter_permission() {
  return array(
    'edit all subscriptions' => array(
      'title' => t('Edit all subscriptions'),
      'description' => t('To edit subscriptions of all users'),
    ),
  );
}

/**
 * Implement hook_menu_alter()
 */
function subscriptions_alter_menu_alter(&$items) {
  $items['user/%user/subscriptions']['access callback'] = '_subscriptions_alter_access';
  foreach (subscriptions_types() as $stype => $data) {
    $items["user/%user/subscriptions/$stype"]['access callback'] = '_subscriptions_alter_access';
  }
}

/**
 * See ../subscriptions/subscriptions.module: _subscriptions_access()
 */
function _subscriptions_alter_access($account, $access = NULL) {
  return _subscriptions_access($account, $access) || ($account && $account->uid && user_access('edit all subscriptions'));
}
